#pragma once

#define ONESHOT_TAP_TOGGLE 3
#define ONESHOT_TIMEOUT 1000

#define TAPPING_TERM 220
#define PERMISSIVE_HOLD

#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY

#define QUICK_TAP_TERM 0

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
