#pragma once

#define ONESHOT_TAP_TOGGLE 5
#define ONESHOT_TIMEOUT 1000

#define TAPPING_TERM 190
#define PERMISSIVE_HOLD

#define QUICK_TAP_TERM 0

#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define CAPS_WORD_INVERT_ON_SHIFT
